### ISSUE TITLE
Use fakeroot

### ISSUE THREAD

**Issue by slendidev** [resslr/aurc#5]
Using fakeroot can be very beneficial so that when building, if a package is malicious, it cannot destroy your system.

**Comment by resslr** [comment]
Fixing now

**Comment by resslr** [comment]
Already uses fakeroot, if I implement fakeroot checking it will break the installation (makepkg is not allowed to be ran as root anyway)

**Comment by resslr** [comment]
Appreciate the concern, if it was possible to run as root would implement :D
